# Generated by Django 5.2.7 on 2025-11-23 18:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medicines", "0001_initial"),
        ("pharmacies", "0001_initial"),
        ("stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("completed", "Complété"),
                            ("abandoned", "Abandonné"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Statut du panier",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création du panier"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Dernière mise à jour du panier"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur propriétaire du panier",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Panier",
                "verbose_name_plural": "Paniers",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantité commandée",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire au moment de l'ajout au panier",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date d'ajout au panier"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Dernière modification"
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="Panier auquel appartient cet article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        help_text="Médicament ajouté au panier",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="medicines.medicine",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        help_text="Pharmacie où acheter le médicament",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="pharmacies.pharmacy",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Référence au stock de la pharmacie",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article du panier",
                "verbose_name_plural": "Articles du panier",
                "ordering": ["-added_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["user", "status"], name="cart_cart_user_id_2c8a21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["-updated_at"], name="cart_cart_updated_758c74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "medicine"], name="cart_cartit_cart_id_3e0e45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["-added_at"], name="cart_cartit_added_a_9af1d6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "medicine", "pharmacy")},
        ),
    ]
