"""
Django settings for FindPharma project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='une_cle_secrete_par_defaut_moins_securisee')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = []


# Application definition

# Base installed apps. We conditionally include the GIS contrib app
# when not running tests AND when not using SQLite to avoid importing
# system-level GIS libs (GDAL) during tests or local dev.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'core',
    'pharmacies',
    'medicines',
    'users',
    'stocks',
    'cart',
    'reservations',
    'django_filters',
    'drf_spectacular',
]

# Add GIS contrib app only when not running tests and not using SQLite.
# This needs to be checked BEFORE we set USE_SQLITE below.
USE_SQLITE_CHECK = config('USE_SQLITE', default=False, cast=bool)
USE_POSTGRES_FOR_TESTS_CHECK = config('USE_POSTGRES_FOR_TESTS', default=False, cast=bool)
if (('test' not in sys.argv or USE_POSTGRES_FOR_TESTS_CHECK) and not USE_SQLITE_CHECK):
    INSTALLED_APPS.insert(6, 'django.contrib.gis')
    INSTALLED_APPS.append('leaflet')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FindPharma.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FindPharma.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {}

# Use a lightweight SQLite DB when running tests OR when USE_SQLITE
# environment variable is set to avoid system-level GIS/PostGIS
# dependencies (GDAL) which may not be available locally.
import sys
USE_SQLITE = config('USE_SQLITE', default=False, cast=bool)
# Allow forcing PostgreSQL for tests with USE_POSTGRES_FOR_TESTS=True
USE_POSTGRES_FOR_TESTS = config('USE_POSTGRES_FOR_TESTS', default=False, cast=bool)

if (('test' in sys.argv and not USE_POSTGRES_FOR_TESTS) or USE_SQLITE):
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
else:
    DATABASES['default'] = {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': config('DATABASE_NAME', default='findpharma'),
        'USER': config('DATABASE_USER', default='findpharmauser'),
        'PASSWORD': config('DATABASE_PASSWORD', default='root'),
        'HOST': config('DATABASE_HOST', default='localhost'),
        'PORT': config('DATABASE_PORT', default='5432'),
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration REST Framework
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# Configuration JWT (Simple JWT)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'FindPharma',
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
    
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Configuration Swagger/OpenAPI
SPECTACULAR_SETTINGS = {
    'TITLE': 'FindPharma API',
    'DESCRIPTION': 'API pour trouver des pharmacies et médicaments à proximité',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# Configuration Leaflet
LEAFLET_CONFIG = {
    'DEFAULT_CENTER': (3.8480, 11.5021),  # Centre de Yaoundé
    'DEFAULT_ZOOM': 12,
    'MIN_ZOOM': 3,
    'MAX_ZOOM': 18,
    'TILES': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    'ATTRIBUTION_PREFIX': 'FindPharma',
}

# Custom User Model
# ========================================
AUTH_USER_MODEL = 'users.User'

# Configuration CORS pour développement
# ========================================
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Configuration des sessions pour fonctionner avec React
# ========================================
# SESSION_COOKIE_DOMAIN laissé à None pour accepter 127.0.0.1 (les IP ne fonctionnent pas comme domaine)
SESSION_COOKIE_SAMESITE = 'Lax'  # ✅ 'Lax' pour dev HTTP (None nécessite HTTPS avec Secure=True)
SESSION_COOKIE_SECURE = False  # False en dev (HTTP), True en prod (HTTPS)
SESSION_COOKIE_HTTPONLY = True  # Protection XSS
SESSION_COOKIE_AGE = 1209600  # 2 semaines
# CSRF_COOKIE_DOMAIN laissé à None également
CSRF_COOKIE_SAMESITE = 'Lax'  # ✅ Même config que SESSION
CSRF_COOKIE_SECURE = False  # False en dev

# ============================================================
# CONFIGURATION EMAIL
# ============================================================

# Pour le développement : utiliser la console (mettre False pour tester les vrais emails)
if False:  # Mode SMTP activé - Les emails sont envoyés par Gmail
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Pour la production : utiliser un vrai serveur SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='FindPharma <noreply@findpharma.cm>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Durée de validité du code de vérification (en minutes)
EMAIL_VERIFICATION_CODE_EXPIRY = 3

# Nombre maximum de tentatives de vérification
MAX_VERIFICATION_ATTEMPTS = 5