# Generated by Django 5.2.7 on 2025-12-22 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacies", "0002_pharmacyreview"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pharmacy",
            options={
                "ordering": ["name"],
                "verbose_name": "Pharmacie",
                "verbose_name_plural": "Pharmacies",
            },
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de validation"),
                    ("approved", "Approuvée"),
                    ("rejected", "Refusée"),
                ],
                default="approved",
                help_text="Les nouvelles pharmacies sont en attente jusqu'à validation admin",
                max_length=20,
                verbose_name="Statut d'approbation",
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'approbation"
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_pharmacies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Approuvé par",
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="license_number",
            field=models.CharField(
                blank=True,
                help_text="Numéro d'agrément officiel de la pharmacie (ex: CAM-PHARM-2024-XXXX)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Numéro d'agrément",
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Explication si la demande a été refusée",
                null=True,
                verbose_name="Motif de refus",
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Utilisateur ayant soumis la demande d'inscription",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_pharmacies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Soumis par",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="address",
            field=models.TextField(verbose_name="Adresse complète"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="latitude",
            field=models.FloatField(verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="longitude",
            field=models.FloatField(verbose_name="Longitude"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nom de la pharmacie"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="opening_hours",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Horaires d'ouverture"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière modification"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(
                fields=["approval_status"], name="pharmacies__approva_7a4aca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(
                fields=["license_number"], name="pharmacies__license_f09a67_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(
                fields=["is_active", "approval_status"],
                name="pharmacies__is_acti_05cb98_idx",
            ),
        ),
    ]
