# Generated by Django 5.2.7 on 2025-12-01 12:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("medicines", "0001_initial"),
        ("pharmacies", "0001_initial"),
        ("stocks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_number",
                    models.CharField(
                        editable=False,
                        help_text="Numéro unique de réservation (ex: RES-2025-XXXX)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("ready", "Prête"),
                            ("collected", "Récupérée"),
                            ("cancelled", "Annulée"),
                            ("expired", "Expirée"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="État actuel de la réservation",
                        max_length=20,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        help_text="Nom de la personne qui viendra récupérer",
                        max_length=100,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(help_text="Téléphone de contact", max_length=20),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email pour les notifications (optionnel)",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "pickup_date",
                    models.DateTimeField(
                        help_text="Date et heure souhaitées pour la récupération"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Instructions ou commentaires spéciaux",
                        null=True,
                    ),
                ),
                (
                    "pharmacy_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes de la pharmacie (ex: raison d'annulation)",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date de création de la réservation",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Dernière mise à jour"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de confirmation par la pharmacie",
                        null=True,
                    ),
                ),
                (
                    "ready_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date où la commande est devenue prête",
                        null=True,
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de récupération effective",
                        null=True,
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="Date d'annulation", null=True
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date d'expiration de la réservation si non récupérée",
                        null=True,
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur qui a annulé la réservation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        help_text="Pharmacie où récupérer la réservation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="pharmacies.pharmacy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Client qui a effectué la réservation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réservation",
                "verbose_name_plural": "Réservations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantité réservée",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prix unitaire au moment de la réservation",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "stock_decremented",
                    models.BooleanField(
                        default=False, help_text="Indique si le stock a été décrémenté"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date d'ajout à la réservation"
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        help_text="Médicament réservé",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_items",
                        to="medicines.medicine",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        help_text="Réservation à laquelle appartient cet article",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        blank=True,
                        help_text="Référence au stock de la pharmacie",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_items",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de réservation",
                "verbose_name_plural": "Articles de réservation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["user", "status"], name="reservation_user_id_b23f11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["pharmacy", "status"], name="reservation_pharmac_0434f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["reservation_number"], name="reservation_reserva_3144d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["-created_at"], name="reservation_created_145999_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["pickup_date"], name="reservation_pickup__01d4bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservationitem",
            index=models.Index(
                fields=["reservation", "medicine"],
                name="reservation_reserva_85ad92_idx",
            ),
        ),
    ]
