#!/bin/bash
# Script de test pour vérifier la correction du bug de distance

echo "=============================================="
echo "🧪 Test de Vérification - Bug Distance Corrigé"
echo "=============================================="
echo ""

# Couleurs
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "📊 État des conteneurs:"
podman ps --format "table {{.Names}}\t{{.Status}}" | grep findpharma

echo ""
echo "=============================================="
echo "🌐 URLs de l'application:"
echo "=============================================="
echo -e "${GREEN}Frontend:${NC} http://localhost:3000"
echo -e "${GREEN}Backend API:${NC} http://localhost:8000/api"
echo -e "${GREEN}Admin Django:${NC} http://localhost:8000/admin"

echo ""
echo "=============================================="
echo "✅ Vérifications à faire manuellement:"
echo "=============================================="
echo ""
echo "1. Ouvrir http://localhost:3000 dans votre navigateur"
echo "2. Se connecter avec un compte utilisateur"
echo "3. Chercher un médicament (ex: 'Paracétamol')"
echo "4. Vérifier les distances affichées:"
echo ""
echo -e "   ${RED}❌ AVANT (Bug):${NC}"
echo "      - Les distances étaient affichées comme '3 m', '10 m', etc."
echo "      - Beaucoup trop petites (1000x trop petites)"
echo ""
echo -e "   ${GREEN}✅ APRÈS (Corrigé):${NC}"
echo "      - Les distances doivent maintenant afficher '3.2 km', '10.5 km', etc."
echo "      - Ou '500 m' pour des distances < 1 km"
echo ""
echo "=============================================="
echo "🔍 Test avec l'API directement:"
echo "=============================================="
echo ""
echo "Exemple de requête API (Centre-ville Yaoundé):"
echo ""
echo "curl 'http://localhost:8000/api/medicines/search/?q=Paracetamol&latitude=3.8667&longitude=11.5167&max_distance=10' | jq '.results[0].pharmacies[0].distance'"
echo ""
echo "La distance retournée devrait être en KILOMÈTRES (ex: 3.23, pas 3231)"
echo ""
echo "=============================================="
echo "📝 Fichiers modifiés:"
echo "=============================================="
echo ""
echo "✅ /frontend/src/services/api.js - Fonction formatDistance() corrigée"
echo "✅ /docs/BUG_DISTANCES_TROP_PETITES.md - Documentation complète"
echo "✅ /docs/ORGANISATION_CALCUL_DISTANCE.md - Mise à jour"
echo ""
echo "=============================================="
echo "🎯 Exemple de ce qui devrait s'afficher:"
echo "=============================================="
echo ""
echo "Pharmacie A - 500 m   ✅ (au lieu de '1 m' ❌)"
echo "Pharmacie B - 1.5 km  ✅ (au lieu de '2 m' ❌)"
echo "Pharmacie C - 3.2 km  ✅ (au lieu de '3 m' ❌)"
echo "Pharmacie D - 10.0 km ✅ (au lieu de '10 m' ❌)"
echo ""
echo "=============================================="
echo "💡 Conseil:"
echo "=============================================="
echo ""
echo "Si les distances semblent encore incorrectes:"
echo "1. Vider le cache du navigateur (Ctrl+Shift+R)"
echo "2. Vérifier que vous êtes bien sur http://localhost:3000"
echo "3. Ouvrir la console du navigateur (F12) pour voir les erreurs"
echo ""
echo "=============================================="
echo "✅ Test terminé!"
echo "=============================================="
