# Generated by Django 5.2.7 on 2025-11-23 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="Terme de recherche utilisé", max_length=255
                    ),
                ),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("medicine", "Recherche de médicament"),
                            ("nearby", "Recherche de pharmacies à proximité"),
                        ],
                        default="medicine",
                        help_text="Type de recherche effectuée",
                        max_length=20,
                    ),
                ),
                (
                    "results_count",
                    models.IntegerField(
                        default=0, help_text="Nombre de résultats trouvés"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date et heure de la recherche"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur ayant effectué la recherche",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de recherche",
                "verbose_name_plural": "Historiques de recherche",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_searc_user_id_0adb08_idx",
                    ),
                    models.Index(
                        fields=["search_type"], name="users_searc_search__491b6c_idx"
                    ),
                ],
            },
        ),
    ]
