# Generated by Django 5.2.7 on 2025-11-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_searchhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code de vérification à 6 caractères", max_length=6
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création du code"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Date d'expiration du code"),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False, help_text="Le code a-t-il été utilisé ?"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Nombre de tentatives de vérification"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur à vérifier",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vérification Email",
                "verbose_name_plural": "Vérifications Email",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_email_user_id_40c57b_idx",
                    ),
                    models.Index(
                        fields=["code", "is_used"], name="users_email_code_ff90d2_idx"
                    ),
                ],
            },
        ),
    ]
