# Generated by Django 5.2.7 on 2025-12-22 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pharmacies", "0003_alter_pharmacy_options_pharmacy_approval_status_and_more"),
        ("users", "0003_add_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("approved", "Approuvé"),
                    ("rejected", "Refusé"),
                ],
                default="approved",
                help_text="Statut d'approbation du compte (pending pour les nouvelles pharmacies)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="Date d'approbation du compte", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin ayant approuvé le compte",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                help_text="Motif de refus si le compte a été rejeté",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["approval_status", "user_type"],
                name="users_user_approva_328ac3_idx",
            ),
        ),
    ]
