# Generated by Django 5.2.7 on 2025-12-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Médicament', 'verbose_name_plural': 'Médicaments'},
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('analgesique', 'Analgésique / Antidouleur'), ('antibiotique', 'Antibiotique'), ('antipaludeen', 'Antipaludéen'), ('antiviral', 'Antiviral'), ('anti_inflammatoire', 'Anti-inflammatoire'), ('antihistaminique', 'Antihistaminique'), ('antidiabetique', 'Antidiabétique'), ('antihypertenseur', 'Antihypertenseur'), ('cardiovasculaire', 'Cardiovasculaire'), ('digestif', 'Système digestif'), ('respiratoire', 'Système respiratoire'), ('dermatologique', 'Dermatologique'), ('ophtalmologique', 'Ophtalmologique'), ('vitamine', 'Vitamines et suppléments'), ('contraceptif', 'Contraceptif'), ('antiparasitaire', 'Antiparasitaire'), ('psychotrope', 'Psychotrope'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='contraindications',
            field=models.TextField(blank=True, help_text='Cas où le médicament ne doit pas être utilisé', null=True, verbose_name='Contre-indications'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name="URL de l'image"),
        ),
        migrations.AddField(
            model_name='medicine',
            name='indications',
            field=models.TextField(blank=True, help_text='À quoi sert ce médicament', null=True, verbose_name='Indications'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='posology',
            field=models.TextField(blank=True, help_text='Dosage recommandé et fréquence de prise', null=True, verbose_name='Posologie'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Effets indésirables possibles', null=True, verbose_name='Effets secondaires'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True, verbose_name='Source Wikipedia'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='average_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix moyen'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forme'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='requires_prescription',
            field=models.BooleanField(default=False, verbose_name='Ordonnance requise'),
        ),
    ]
